baseURL = "https://pgregory.net/"
languageCode = "en-us"
title = "Gregory Petrosyan's home page"
theme = "plain"
publishDir = "docs"
disableHugoGeneratorInject = true
enableGitInfo = true

[params]
  Description = "Test home page description"
