baseURL = "https://pgregory.net/"
languageCode = "en-us"
title = "Gregory Petrosyan's home page"
theme = "plain"
publishDir = "docs"
disableHugoGeneratorInject = true
enableGitInfo = true

[params]
  description = "Test home page description"
  navRoot = "pgregory.net"

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 8
